// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReactStore.Infrastructure;

namespace ReactStore.API.Migrations
{
    [DbContext(typeof(ReactStoreContext))]
    [Migration("20210607155918_AddProductVariants")]
    partial class AddProductVariants
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ReactStore.Domain.Entities.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("ReactStore.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("ReactStore.Domain.Entities.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Brands", "reactstore");

                    b.HasData(
                        new
                        {
                            Id = new Guid("183292a1-aa68-47d2-8274-53db45ba4f9d"),
                            Name = "Apple"
                        },
                        new
                        {
                            Id = new Guid("f157b0c8-9d2d-40c3-9c54-8861a4e11104"),
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = new Guid("44b587b4-df67-4d47-b18b-73d864a532a4"),
                            Name = "Google"
                        },
                        new
                        {
                            Id = new Guid("5d1272dd-5161-4565-a291-376d9f11c6bc"),
                            Name = "Motorola"
                        },
                        new
                        {
                            Id = new Guid("7abd633b-112f-4f9d-8f4a-dc7489e26bc4"),
                            Name = "LG"
                        });
                });

            modelBuilder.Entity("ReactStore.Domain.Entities.Color", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colors", "reactstore");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8edc4495-ca80-429d-a3ec-7c77df818fca"),
                            Name = "Black"
                        },
                        new
                        {
                            Id = new Guid("e762254a-77e6-4886-b327-ae6b71a0be1f"),
                            Name = "White"
                        },
                        new
                        {
                            Id = new Guid("598fd40c-9148-47ad-8cc1-d03a510a5e57"),
                            Name = "Blue"
                        },
                        new
                        {
                            Id = new Guid("d1e1131a-0382-40f6-9c07-c2f0c943cca1"),
                            Name = "Green"
                        },
                        new
                        {
                            Id = new Guid("a2dee3a0-6efa-418b-b3d0-3f0256d42317"),
                            Name = "Purple"
                        },
                        new
                        {
                            Id = new Guid("9e51ef2d-7487-4f31-aaaf-b3a607266c40"),
                            Name = "Red"
                        },
                        new
                        {
                            Id = new Guid("baedceea-bcce-4a04-a751-23f0f74a7469"),
                            Name = "Red"
                        },
                        new
                        {
                            Id = new Guid("2bb98aa1-d207-4db1-afcc-51315827bf31"),
                            Name = "Pink"
                        },
                        new
                        {
                            Id = new Guid("c2be3452-add3-4342-8abc-10a7d17cc890"),
                            Name = "Grey"
                        });
                });

            modelBuilder.Entity("ReactStore.Domain.Entities.Feature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Features", "reactstore");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20788b1b-d5be-4b96-b02a-547243555435"),
                            Name = "5G"
                        },
                        new
                        {
                            Id = new Guid("0563b571-9fe2-4b13-ad37-531c16bfd7f5"),
                            Name = "4G"
                        },
                        new
                        {
                            Id = new Guid("7c14439b-6e59-4640-96c6-94255280773d"),
                            Name = "Memory Expandable"
                        },
                        new
                        {
                            Id = new Guid("0bbef1d6-fb69-4393-a84d-f7d7af542f16"),
                            Name = "USB-C Connector"
                        },
                        new
                        {
                            Id = new Guid("789f70b2-77d7-4f40-a530-4cff8dff1420"),
                            Name = "Fast Charger"
                        },
                        new
                        {
                            Id = new Guid("0238da59-e7d2-4f5a-80ca-928afdfb235a"),
                            Name = "Wireless  Charging"
                        });
                });

            modelBuilder.Entity("ReactStore.Domain.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Images", "reactstore");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9237edb-d19d-4499-ab69-86cb2adb90de"),
                            ProductId = new Guid("7e60cf5a-0aab-49d5-9ef2-3f2c9b0f097d"),
                            Url = "https://localhost:5001/galaxys21ultra/samsung-s21-ultra.png"
                        },
                        new
                        {
                            Id = new Guid("f42d0fa4-bcf0-4625-9bf6-8778f59e74d6"),
                            ProductId = new Guid("7e60cf5a-0aab-49d5-9ef2-3f2c9b0f097d"),
                            Url = "https://localhost:5001/galaxys21ultra/samsung-s21-ultra1.png"
                        },
                        new
                        {
                            Id = new Guid("f60b33e2-8738-4854-a183-b41dd0540315"),
                            ProductId = new Guid("7e60cf5a-0aab-49d5-9ef2-3f2c9b0f097d"),
                            Url = "https://localhost:5001/galaxys21ultra/samsung-s21-ultra2.png"
                        },
                        new
                        {
                            Id = new Guid("01cfbbf9-3f51-442c-b6a2-561272effb5b"),
                            ProductId = new Guid("7e60cf5a-0aab-49d5-9ef2-3f2c9b0f097d"),
                            Url = "https://localhost:5001/galaxys21ultra/samsung-s21-ultra3.png"
                        },
                        new
                        {
                            Id = new Guid("1599de96-9e96-4f77-9217-e11cc58952d4"),
                            ProductId = new Guid("533ed09f-6a3a-4ad7-922f-76ebc4a9bc30"),
                            Url = "https://localhost:5001/galaxynote20/galaxy-note20.png"
                        },
                        new
                        {
                            Id = new Guid("6ab70b21-6902-4d10-82e7-dab51fcddfe4"),
                            ProductId = new Guid("533ed09f-6a3a-4ad7-922f-76ebc4a9bc30"),
                            Url = "https://localhost:5001/galaxynote20/galaxy-note20_1.png"
                        },
                        new
                        {
                            Id = new Guid("9f7e191d-f0a0-400f-ab32-f3f0edda0027"),
                            ProductId = new Guid("533ed09f-6a3a-4ad7-922f-76ebc4a9bc30"),
                            Url = "https://localhost:5001/galaxynote20/galaxy-note20_2.png"
                        },
                        new
                        {
                            Id = new Guid("07b94476-8a5f-4cbd-8dcc-d41fe4416dc2"),
                            ProductId = new Guid("533ed09f-6a3a-4ad7-922f-76ebc4a9bc30"),
                            Url = "https://localhost:5001/galaxynote20/galaxy-note20_3.png"
                        },
                        new
                        {
                            Id = new Guid("a178a432-30b7-4a52-9ea6-05b31d4d6768"),
                            ProductId = new Guid("8b94cae3-0ef3-4e2e-bbcd-92ec689d3b73"),
                            Url = "https://localhost:5001/iphone12promax/iphone12-pro.png"
                        },
                        new
                        {
                            Id = new Guid("29f4cf53-dcaa-44eb-ae4f-fd4266a6e2b7"),
                            ProductId = new Guid("8b94cae3-0ef3-4e2e-bbcd-92ec689d3b73"),
                            Url = "https://localhost:5001/iphone12promax/iphone12-pro1.png"
                        },
                        new
                        {
                            Id = new Guid("f02b04db-3c65-4f82-b1f7-40aa206601fb"),
                            ProductId = new Guid("8b94cae3-0ef3-4e2e-bbcd-92ec689d3b73"),
                            Url = "https://localhost:5001/iphone12promax/iphone12-pro2.png"
                        },
                        new
                        {
                            Id = new Guid("5021c75c-23ab-4bf6-afc3-ae3827b639fd"),
                            ProductId = new Guid("8b94cae3-0ef3-4e2e-bbcd-92ec689d3b73"),
                            Url = "https://localhost:5001/iphone12promax/iphone12-pro3.png"
                        },
                        new
                        {
                            Id = new Guid("8873a4d7-a079-4446-9b56-82c64386e834"),
                            ProductId = new Guid("d96901d6-44aa-4d67-b616-a347966df5a2"),
                            Url = "https://localhost:5001/iphone12/iphone-12.png"
                        },
                        new
                        {
                            Id = new Guid("5171533e-155d-444c-b10c-d6d132cf642a"),
                            ProductId = new Guid("d96901d6-44aa-4d67-b616-a347966df5a2"),
                            Url = "https://localhost:5001/iphone12/iphone-12_1.png"
                        },
                        new
                        {
                            Id = new Guid("0b69f38f-6775-4de5-afd9-f1af2986172d"),
                            ProductId = new Guid("d96901d6-44aa-4d67-b616-a347966df5a2"),
                            Url = "https://localhost:5001/iphone12/iphone-12_2.png"
                        },
                        new
                        {
                            Id = new Guid("c64b5c10-edf1-4eaf-be41-617cc13e56b8"),
                            ProductId = new Guid("a3478123-d608-4032-b447-b634a2dec89c"),
                            Url = "https://localhost:5001/iphone12mini/iphone-12-mini.png"
                        },
                        new
                        {
                            Id = new Guid("c0745c79-0011-412b-bfeb-ca144e6b36c0"),
                            ProductId = new Guid("a3478123-d608-4032-b447-b634a2dec89c"),
                            Url = "https://localhost:5001/iphone12mini/iphone-12-mini1.png"
                        },
                        new
                        {
                            Id = new Guid("43226ce5-2a1f-4b6f-b582-6d0f88720071"),
                            ProductId = new Guid("a3478123-d608-4032-b447-b634a2dec89c"),
                            Url = "https://localhost:5001/iphone12mini/iphone-12-mini2.png"
                        },
                        new
                        {
                            Id = new Guid("70812869-16e6-4b0f-ae2b-5a351dc3bf77"),
                            ProductId = new Guid("a3478123-d608-4032-b447-b634a2dec89c"),
                            Url = "https://localhost:5001/iphone12mini/iphone-12-mini3.png"
                        },
                        new
                        {
                            Id = new Guid("257fe54c-5631-4cc3-90db-6774a81784fe"),
                            ProductId = new Guid("5b5087a0-5cac-4fde-b39d-d6fbdb7f5d57"),
                            Url = "https://localhost:5001/google5/google-pixel5.png"
                        },
                        new
                        {
                            Id = new Guid("ba440eba-5cdf-4de8-b505-f64ae27d422c"),
                            ProductId = new Guid("5b5087a0-5cac-4fde-b39d-d6fbdb7f5d57"),
                            Url = "https://localhost:5001/google5/google-pixel5_1.png"
                        },
                        new
                        {
                            Id = new Guid("0904aecd-7d17-4687-8295-b843ddd16725"),
                            ProductId = new Guid("5b5087a0-5cac-4fde-b39d-d6fbdb7f5d57"),
                            Url = "https://localhost:5001/google5/google-pixel5_2.png"
                        },
                        new
                        {
                            Id = new Guid("ffc14ddd-e7ce-47e6-8ac8-e9c0491e0d2a"),
                            ProductId = new Guid("5b5087a0-5cac-4fde-b39d-d6fbdb7f5d57"),
                            Url = "https://localhost:5001/google5/google-pixel5_3.png"
                        },
                        new
                        {
                            Id = new Guid("a37fc52d-bc1e-4342-89cb-8c819ae18099"),
                            ProductId = new Guid("fc386a0a-48a8-49e9-aff7-e0bf6902d3b3"),
                            Url = "https://localhost:5001/galaxys21/samsung-s21.png"
                        },
                        new
                        {
                            Id = new Guid("d11741be-06b2-4ba7-b51e-f3cdddec0bde"),
                            ProductId = new Guid("fc386a0a-48a8-49e9-aff7-e0bf6902d3b3"),
                            Url = "https://localhost:5001/galaxys21/samsung-s21_1.png"
                        },
                        new
                        {
                            Id = new Guid("0e91ed42-d29e-4d7a-80f6-c3377d20663b"),
                            ProductId = new Guid("fc386a0a-48a8-49e9-aff7-e0bf6902d3b3"),
                            Url = "https://localhost:5001/galaxys21/samsung-s21_2.png"
                        },
                        new
                        {
                            Id = new Guid("990332da-6dd0-48e4-9ae9-57faafb966d8"),
                            ProductId = new Guid("fc386a0a-48a8-49e9-aff7-e0bf6902d3b3"),
                            Url = "https://localhost:5001/galaxys21/samsung-s21_3.png"
                        });
                });

            modelBuilder.Entity("ReactStore.Domain.Entities.OS", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OS", "reactstore");

                    b.HasData(
                        new
                        {
                            Id = new Guid("471ede3e-8585-4850-ac51-0fb4c5ce74fd"),
                            Name = "Android"
                        },
                        new
                        {
                            Id = new Guid("626a0fcd-d831-4bf9-8e23-a33ed73e7f67"),
                            Name = "iOS"
                        });
                });

            modelBuilder.Entity("ReactStore.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OSId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ScreenSize")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("StandByTime")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("TalkTime")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("OSId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Products", "reactstore");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d3903dec-87fa-4772-a705-10cd694aa534"),
                            BrandId = new Guid("6213ab61-e37d-40fe-9fd9-61ea21fba50b"),
                            Description = "The best iPhone display ever for incredible contrast and higher resolution. With Ceramic Shield, which has four times better drop performance. Superfast speeds. Superlow latency. So you can get faster downloads, better-quality video streaming, more responsive gaming and real-time interactivity. A14 Bionic is the fastest chip in a smartphone. With a 16-core Neural Engine, it crunches trillions of operations each second. And it’s superefficient for great battery life. ",
                            Name = "iPhone 12 mini",
                            OSId = new Guid("bc052339-a7a9-429f-a673-b03589b84fad"),
                            ScreenSize = 5.4m,
                            ShortDescription = "iPhone 12 Mini, 5G speed. A14 Bionic, the fastest chip in a smartphone. An edge-to-edge OLED display",
                            Slug = "iphone-12-mini",
                            StandByTime = 32m,
                            TalkTime = 18m,
                            Thumbnail = "https://localhost:5001/thumbnails/iphone-12-mini.png"
                        },
                        new
                        {
                            Id = new Guid("773e7553-d8c5-4882-9556-fcce65713eed"),
                            BrandId = new Guid("6213ab61-e37d-40fe-9fd9-61ea21fba50b"),
                            Description = "The best iPhone display ever for incredible contrast and higher resolution. With Ceramic Shield, which has four times better drop performance. Superfast speeds. Superlow latency. So you can get faster downloads, better-quality video streaming, more responsive gaming and real-time interactivity.A14 Bionic is the fastest chip in a smartphone. With a 16-core Neural Engine, it crunches trillions of operations each second. And it’s superefficient for great battery life.",
                            Name = "iPhone 12",
                            OSId = new Guid("bc052339-a7a9-429f-a673-b03589b84fad"),
                            ScreenSize = 6.1m,
                            ShortDescription = "iPhone 12, 5G speed. A14 Bionic, the fastest chip in a smartphone. An edge-to-edge OLED display.. And Night mode on every camera.",
                            Slug = "iphone-12",
                            StandByTime = 32m,
                            TalkTime = 18m,
                            Thumbnail = "https://localhost:5001/thumbnails/iphone-12.png"
                        },
                        new
                        {
                            Id = new Guid("f24404a7-f458-4c17-9ae6-edfaa7e5bc36"),
                            BrandId = new Guid("6213ab61-e37d-40fe-9fd9-61ea21fba50b"),
                            Description = "The Super Retina XDR display goes edge to edge. With Ceramic Shield, which has four times better drop performance. Superfast speeds. Superlow latency. So you can get faster downloads, better-quality video streaming, more responsive gaming and real-time interactivity. Introducing the first 5-nanometre chip in the industry. Which means more speed, more power and more efficiency. LiDAR creates accurate depth maps in nanoseconds, so objects are placed instantly and more accurately in AR experiences.",
                            Name = "iPhone 12 Pro Max",
                            OSId = new Guid("bc052339-a7a9-429f-a673-b03589b84fad"),
                            ScreenSize = 6.7m,
                            ShortDescription = "iPhone 12 Pro Max, 5G speed. A14 Bionic, the fastest chip in a smartphone. And a Pro camera system that takes low-light photography to the next level — with an even bigger jump on iPhone 12 Pro Max.",
                            Slug = "iphone-12-pro-max",
                            StandByTime = 32m,
                            TalkTime = 18m,
                            Thumbnail = "https://localhost:5001/thumbnails/iphone-12-pro-max.png"
                        },
                        new
                        {
                            Id = new Guid("2274e726-a3a1-4473-98f1-4db8ca19fa35"),
                            BrandId = new Guid("8ab3a1c4-0b52-4671-ab2a-753e28c1a0be"),
                            Description = "With 5G,you can download your favourite movies on the go and start watching before you know it. Go from game time to show time, all in crystal clear HD. Pixel’s 5G hotspot is powerful enough to keep multiple devices connected at once. HDR+ automatically enhances colour and lighting, so the photos that you take stay as vivid as you remember. With HD Duo screen sharing, you can read articles, watch live sports, and laugh together as if you were sitting in the same room. Adaptive Battery reduces power to the apps that you rarely use, so your mobile phone keeps its charge all day.",
                            Name = "Google Pixel 5",
                            OSId = new Guid("c81d73b4-2d7e-4ae8-8802-057dda516f79"),
                            ScreenSize = 5.9m,
                            ShortDescription = "Pixel 5, The best of Google in 5G. Have a photo shoot day or night, capture moments with stunning clarity, and take clips with Hollywood-inspired effects.",
                            Slug = "google-pixel-5",
                            StandByTime = 32m,
                            TalkTime = 18m,
                            Thumbnail = "https://localhost:5001/thumbnails/google-pixel-5.png"
                        },
                        new
                        {
                            Id = new Guid("a4e31e86-1a3f-4aa7-bbd5-d2b21bb3c118"),
                            BrandId = new Guid("7360baa4-71c3-442d-9328-7f9cfbdf5e1f"),
                            Description = "This isn't the time to slow down, this is the time to forge ahead and take the opportunities that come your way. You don’t need a smartphone. You need a power phone. One as beautiful as it is intelligent with a pen that is mighty, a battery that doesn't leave you hanging and is as well-connected as you are. The Galaxy Note20 5G and Galaxy Note20 Ultra 5G take power to the next level with cutting-edge technology, letting you master whatever you choose to do next. The Galaxy Note20 5G and Galaxy Note20 Ultra 5G have a big battery. Big enough to last all day. But that's not all, it's also intelligent. The Galaxy Note20 5G and Galaxy Note20 Ultra 5G intuitively manage your app usage to conserve energy on its own so you don't need to. Rest assured that you can tackle those emails during the day and be left with enough power to tackle your opponents at night. And if you are running low on battery, get hours of power from minutes of charge with Super Fast Charging.",
                            Name = "Samsung Galaxy Note20",
                            OSId = new Guid("c81d73b4-2d7e-4ae8-8802-057dda516f79"),
                            ScreenSize = 7m,
                            ShortDescription = "This isn't the time to slow down, this is the time to forge ahead and take the opportunities that come your way.",
                            Slug = "samsung-galaxy-note-20",
                            StandByTime = 32m,
                            TalkTime = 18m,
                            Thumbnail = "https://localhost:5001/thumbnails/galaxy-note20.png"
                        },
                        new
                        {
                            Id = new Guid("3b01fb18-08cd-499c-900d-879e491a77f9"),
                            BrandId = new Guid("7360baa4-71c3-442d-9328-7f9cfbdf5e1f"),
                            Description = "Create share-ready GIFs and videos in one take1 or pick your favourite moments and pull your favorite stills in super high res to share with your followers. Zoom in close, take photos and videos like a pro, and capture incredible share-ready moments with our easy-to-use, multi-lens camera. Power every scroll, click, tap, and stream all day long and then some with an intelligent battery that works with you, not against you. A night out. Your best friend's birthday party. Family moments you'll want to remember forever. Capture your life's best moments in head-turning, super smooth 8K video.",
                            Name = "Samsung Galaxy S21 Ultra",
                            OSId = new Guid("c81d73b4-2d7e-4ae8-8802-057dda516f79"),
                            ScreenSize = 7m,
                            ShortDescription = "Spontaneity, now captured from multiple angles. A camera so good, everyone's a pro. All-day battery, and then some. Trust us, you'll look amazing in 8K video.",
                            Slug = "samsung-galaxy-s21-ultra",
                            StandByTime = 32m,
                            TalkTime = 18m,
                            Thumbnail = "https://localhost:5001/thumbnails/galaxy-s21-ultra.png"
                        },
                        new
                        {
                            Id = new Guid("bbf68dd5-56c3-4133-a818-c417e8692c27"),
                            BrandId = new Guid("7360baa4-71c3-442d-9328-7f9cfbdf5e1f"),
                            Description = "Create share-ready GIFs and videos in one take1 or pick your favourite moments and pull your favorite stills in super high res to share with your followers. Zoom in close, take photos and videos like a pro, and capture incredible share-ready moments with our easy-to-use, multi-lens camera. Power every scroll, click, tap, and stream all day long and then some with an intelligent battery that works with you, not against you. A night out. Your best friend's birthday party. Family moments you'll want to remember forever. Capture your life's best moments in head-turning, super smooth 8K video.",
                            Name = "Samsung Galaxy S21",
                            OSId = new Guid("c81d73b4-2d7e-4ae8-8802-057dda516f79"),
                            ScreenSize = 6m,
                            ShortDescription = "Spontaneity, now captured from multiple angles. A camera so good, everyone's a pro. All-day battery, and then some. Trust us, you'll look amazing in 8K video.",
                            Slug = "samsung-galaxy-s21",
                            StandByTime = 32m,
                            TalkTime = 18m,
                            Thumbnail = "https://localhost:5001/thumbnails/galaxy-s21.png"
                        });
                });

            modelBuilder.Entity("ReactStore.Domain.Entities.ProductFeature", b =>
                {
                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FeatureId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductFeatures", "reactstore");

                    b.HasData(
                        new
                        {
                            FeatureId = new Guid("aa9fb69a-380a-4c28-968f-61f700750153"),
                            ProductId = new Guid("7e60cf5a-0aab-49d5-9ef2-3f2c9b0f097d")
                        },
                        new
                        {
                            FeatureId = new Guid("e22b3b21-a9dd-4bc8-8995-0660072c1d0b"),
                            ProductId = new Guid("7e60cf5a-0aab-49d5-9ef2-3f2c9b0f097d")
                        },
                        new
                        {
                            FeatureId = new Guid("9f45ed5f-cbeb-4355-a9c2-7aa51ffcc1c9"),
                            ProductId = new Guid("7e60cf5a-0aab-49d5-9ef2-3f2c9b0f097d")
                        },
                        new
                        {
                            FeatureId = new Guid("c225a75f-4805-46d6-bb1b-ce6fda211b0d"),
                            ProductId = new Guid("7e60cf5a-0aab-49d5-9ef2-3f2c9b0f097d")
                        },
                        new
                        {
                            FeatureId = new Guid("aa9fb69a-380a-4c28-968f-61f700750153"),
                            ProductId = new Guid("533ed09f-6a3a-4ad7-922f-76ebc4a9bc30")
                        },
                        new
                        {
                            FeatureId = new Guid("3f66e2b9-ad81-42c7-9923-a7ec1d9fe252"),
                            ProductId = new Guid("533ed09f-6a3a-4ad7-922f-76ebc4a9bc30")
                        },
                        new
                        {
                            FeatureId = new Guid("c225a75f-4805-46d6-bb1b-ce6fda211b0d"),
                            ProductId = new Guid("533ed09f-6a3a-4ad7-922f-76ebc4a9bc30")
                        },
                        new
                        {
                            FeatureId = new Guid("eeb24885-50be-4454-b5c4-53b5678ac8aa"),
                            ProductId = new Guid("533ed09f-6a3a-4ad7-922f-76ebc4a9bc30")
                        },
                        new
                        {
                            FeatureId = new Guid("aa9fb69a-380a-4c28-968f-61f700750153"),
                            ProductId = new Guid("8b94cae3-0ef3-4e2e-bbcd-92ec689d3b73")
                        },
                        new
                        {
                            FeatureId = new Guid("eeb24885-50be-4454-b5c4-53b5678ac8aa"),
                            ProductId = new Guid("8b94cae3-0ef3-4e2e-bbcd-92ec689d3b73")
                        },
                        new
                        {
                            FeatureId = new Guid("c225a75f-4805-46d6-bb1b-ce6fda211b0d"),
                            ProductId = new Guid("8b94cae3-0ef3-4e2e-bbcd-92ec689d3b73")
                        },
                        new
                        {
                            FeatureId = new Guid("9f45ed5f-cbeb-4355-a9c2-7aa51ffcc1c9"),
                            ProductId = new Guid("8b94cae3-0ef3-4e2e-bbcd-92ec689d3b73")
                        },
                        new
                        {
                            FeatureId = new Guid("aa9fb69a-380a-4c28-968f-61f700750153"),
                            ProductId = new Guid("d96901d6-44aa-4d67-b616-a347966df5a2")
                        },
                        new
                        {
                            FeatureId = new Guid("c225a75f-4805-46d6-bb1b-ce6fda211b0d"),
                            ProductId = new Guid("d96901d6-44aa-4d67-b616-a347966df5a2")
                        },
                        new
                        {
                            FeatureId = new Guid("9f45ed5f-cbeb-4355-a9c2-7aa51ffcc1c9"),
                            ProductId = new Guid("d96901d6-44aa-4d67-b616-a347966df5a2")
                        },
                        new
                        {
                            FeatureId = new Guid("aa9fb69a-380a-4c28-968f-61f700750153"),
                            ProductId = new Guid("a3478123-d608-4032-b447-b634a2dec89c")
                        },
                        new
                        {
                            FeatureId = new Guid("9f45ed5f-cbeb-4355-a9c2-7aa51ffcc1c9"),
                            ProductId = new Guid("a3478123-d608-4032-b447-b634a2dec89c")
                        },
                        new
                        {
                            FeatureId = new Guid("aa9fb69a-380a-4c28-968f-61f700750153"),
                            ProductId = new Guid("5b5087a0-5cac-4fde-b39d-d6fbdb7f5d57")
                        },
                        new
                        {
                            FeatureId = new Guid("eeb24885-50be-4454-b5c4-53b5678ac8aa"),
                            ProductId = new Guid("5b5087a0-5cac-4fde-b39d-d6fbdb7f5d57")
                        },
                        new
                        {
                            FeatureId = new Guid("e22b3b21-a9dd-4bc8-8995-0660072c1d0b"),
                            ProductId = new Guid("5b5087a0-5cac-4fde-b39d-d6fbdb7f5d57")
                        },
                        new
                        {
                            FeatureId = new Guid("aa9fb69a-380a-4c28-968f-61f700750153"),
                            ProductId = new Guid("fc386a0a-48a8-49e9-aff7-e0bf6902d3b3")
                        },
                        new
                        {
                            FeatureId = new Guid("e22b3b21-a9dd-4bc8-8995-0660072c1d0b"),
                            ProductId = new Guid("fc386a0a-48a8-49e9-aff7-e0bf6902d3b3")
                        },
                        new
                        {
                            FeatureId = new Guid("eeb24885-50be-4454-b5c4-53b5678ac8aa"),
                            ProductId = new Guid("fc386a0a-48a8-49e9-aff7-e0bf6902d3b3")
                        },
                        new
                        {
                            FeatureId = new Guid("9f45ed5f-cbeb-4355-a9c2-7aa51ffcc1c9"),
                            ProductId = new Guid("fc386a0a-48a8-49e9-aff7-e0bf6902d3b3")
                        },
                        new
                        {
                            FeatureId = new Guid("c225a75f-4805-46d6-bb1b-ce6fda211b0d"),
                            ProductId = new Guid("fc386a0a-48a8-49e9-aff7-e0bf6902d3b3")
                        });
                });

            modelBuilder.Entity("ReactStore.Domain.Entities.ProductVariant", b =>
                {
                    b.Property<Guid>("ColorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StorageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.HasKey("ColorId", "ProductId", "StorageId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StorageId");

                    b.ToTable("ProductVariants", "reactstore");

                    b.HasData(
                        new
                        {
                            ColorId = new Guid("30462f05-b486-4ee0-b2d8-364d5627145d"),
                            ProductId = new Guid("7e60cf5a-0aab-49d5-9ef2-3f2c9b0f097d"),
                            StorageId = new Guid("80c335a6-eaae-42eb-a83a-0d7f47dc543a"),
                            Price = 2040m
                        },
                        new
                        {
                            ColorId = new Guid("30462f05-b486-4ee0-b2d8-364d5627145d"),
                            ProductId = new Guid("7e60cf5a-0aab-49d5-9ef2-3f2c9b0f097d"),
                            StorageId = new Guid("c1d112fd-5a18-415d-9a5f-9cbc602095a2"),
                            Price = 2125m
                        },
                        new
                        {
                            ColorId = new Guid("30462f05-b486-4ee0-b2d8-364d5627145d"),
                            ProductId = new Guid("533ed09f-6a3a-4ad7-922f-76ebc4a9bc30"),
                            StorageId = new Guid("80c335a6-eaae-42eb-a83a-0d7f47dc543a"),
                            Price = 2250m
                        },
                        new
                        {
                            ColorId = new Guid("fee21a32-ec49-46cd-adf9-8ed4b15211c9"),
                            ProductId = new Guid("8b94cae3-0ef3-4e2e-bbcd-92ec689d3b73"),
                            StorageId = new Guid("80c335a6-eaae-42eb-a83a-0d7f47dc543a"),
                            Price = 1596m
                        },
                        new
                        {
                            ColorId = new Guid("fee21a32-ec49-46cd-adf9-8ed4b15211c9"),
                            ProductId = new Guid("8b94cae3-0ef3-4e2e-bbcd-92ec689d3b73"),
                            StorageId = new Guid("c1d112fd-5a18-415d-9a5f-9cbc602095a2"),
                            Price = 1740m
                        },
                        new
                        {
                            ColorId = new Guid("d004ef26-3c08-4f6e-8060-136029b75782"),
                            ProductId = new Guid("8b94cae3-0ef3-4e2e-bbcd-92ec689d3b73"),
                            StorageId = new Guid("80c335a6-eaae-42eb-a83a-0d7f47dc543a"),
                            Price = 14596m
                        },
                        new
                        {
                            ColorId = new Guid("d004ef26-3c08-4f6e-8060-136029b75782"),
                            ProductId = new Guid("8b94cae3-0ef3-4e2e-bbcd-92ec689d3b73"),
                            StorageId = new Guid("c1d112fd-5a18-415d-9a5f-9cbc602095a2"),
                            Price = 1740m
                        },
                        new
                        {
                            ColorId = new Guid("d004ef26-3c08-4f6e-8060-136029b75782"),
                            ProductId = new Guid("8b94cae3-0ef3-4e2e-bbcd-92ec689d3b73"),
                            StorageId = new Guid("52f4cfc5-10a6-41b2-8761-1273de874546"),
                            Price = 2016m
                        },
                        new
                        {
                            ColorId = new Guid("51c347f4-3293-4a63-9170-0531b325548d"),
                            ProductId = new Guid("d96901d6-44aa-4d67-b616-a347966df5a2"),
                            StorageId = new Guid("2183be20-628e-480b-93e9-0b1fefb38120"),
                            Price = 1164m
                        },
                        new
                        {
                            ColorId = new Guid("51c347f4-3293-4a63-9170-0531b325548d"),
                            ProductId = new Guid("d96901d6-44aa-4d67-b616-a347966df5a2"),
                            StorageId = new Guid("80c335a6-eaae-42eb-a83a-0d7f47dc543a"),
                            Price = 1236m
                        },
                        new
                        {
                            ColorId = new Guid("d004ef26-3c08-4f6e-8060-136029b75782"),
                            ProductId = new Guid("d96901d6-44aa-4d67-b616-a347966df5a2"),
                            StorageId = new Guid("2183be20-628e-480b-93e9-0b1fefb38120"),
                            Price = 1164m
                        },
                        new
                        {
                            ColorId = new Guid("d004ef26-3c08-4f6e-8060-136029b75782"),
                            ProductId = new Guid("d96901d6-44aa-4d67-b616-a347966df5a2"),
                            StorageId = new Guid("80c335a6-eaae-42eb-a83a-0d7f47dc543a"),
                            Price = 1236m
                        },
                        new
                        {
                            ColorId = new Guid("d004ef26-3c08-4f6e-8060-136029b75782"),
                            ProductId = new Guid("d96901d6-44aa-4d67-b616-a347966df5a2"),
                            StorageId = new Guid("c1d112fd-5a18-415d-9a5f-9cbc602095a2"),
                            Price = 1380m
                        },
                        new
                        {
                            ColorId = new Guid("700b2a28-ea84-419c-bf6d-7fe1126b4b4b"),
                            ProductId = new Guid("d96901d6-44aa-4d67-b616-a347966df5a2"),
                            StorageId = new Guid("2183be20-628e-480b-93e9-0b1fefb38120"),
                            Price = 1164m
                        },
                        new
                        {
                            ColorId = new Guid("700b2a28-ea84-419c-bf6d-7fe1126b4b4b"),
                            ProductId = new Guid("d96901d6-44aa-4d67-b616-a347966df5a2"),
                            StorageId = new Guid("80c335a6-eaae-42eb-a83a-0d7f47dc543a"),
                            Price = 1236m
                        },
                        new
                        {
                            ColorId = new Guid("700b2a28-ea84-419c-bf6d-7fe1126b4b4b"),
                            ProductId = new Guid("d96901d6-44aa-4d67-b616-a347966df5a2"),
                            StorageId = new Guid("c1d112fd-5a18-415d-9a5f-9cbc602095a2"),
                            Price = 1380m
                        },
                        new
                        {
                            ColorId = new Guid("ea32ab8f-e614-4327-955e-3b26670cc1c9"),
                            ProductId = new Guid("d96901d6-44aa-4d67-b616-a347966df5a2"),
                            StorageId = new Guid("2183be20-628e-480b-93e9-0b1fefb38120"),
                            Price = 1164m
                        },
                        new
                        {
                            ColorId = new Guid("ea32ab8f-e614-4327-955e-3b26670cc1c9"),
                            ProductId = new Guid("d96901d6-44aa-4d67-b616-a347966df5a2"),
                            StorageId = new Guid("80c335a6-eaae-42eb-a83a-0d7f47dc543a"),
                            Price = 1236m
                        },
                        new
                        {
                            ColorId = new Guid("ea32ab8f-e614-4327-955e-3b26670cc1c9"),
                            ProductId = new Guid("d96901d6-44aa-4d67-b616-a347966df5a2"),
                            StorageId = new Guid("c1d112fd-5a18-415d-9a5f-9cbc602095a2"),
                            Price = 1380m
                        },
                        new
                        {
                            ColorId = new Guid("51c347f4-3293-4a63-9170-0531b325548d"),
                            ProductId = new Guid("a3478123-d608-4032-b447-b634a2dec89c"),
                            StorageId = new Guid("2183be20-628e-480b-93e9-0b1fefb38120"),
                            Price = 1008m
                        },
                        new
                        {
                            ColorId = new Guid("51c347f4-3293-4a63-9170-0531b325548d"),
                            ProductId = new Guid("a3478123-d608-4032-b447-b634a2dec89c"),
                            StorageId = new Guid("80c335a6-eaae-42eb-a83a-0d7f47dc543a"),
                            Price = 1080m
                        },
                        new
                        {
                            ColorId = new Guid("d004ef26-3c08-4f6e-8060-136029b75782"),
                            ProductId = new Guid("a3478123-d608-4032-b447-b634a2dec89c"),
                            StorageId = new Guid("2183be20-628e-480b-93e9-0b1fefb38120"),
                            Price = 1008m
                        },
                        new
                        {
                            ColorId = new Guid("d004ef26-3c08-4f6e-8060-136029b75782"),
                            ProductId = new Guid("a3478123-d608-4032-b447-b634a2dec89c"),
                            StorageId = new Guid("80c335a6-eaae-42eb-a83a-0d7f47dc543a"),
                            Price = 1080m
                        },
                        new
                        {
                            ColorId = new Guid("d004ef26-3c08-4f6e-8060-136029b75782"),
                            ProductId = new Guid("a3478123-d608-4032-b447-b634a2dec89c"),
                            StorageId = new Guid("c1d112fd-5a18-415d-9a5f-9cbc602095a2"),
                            Price = 1225m
                        },
                        new
                        {
                            ColorId = new Guid("700b2a28-ea84-419c-bf6d-7fe1126b4b4b"),
                            ProductId = new Guid("a3478123-d608-4032-b447-b634a2dec89c"),
                            StorageId = new Guid("2183be20-628e-480b-93e9-0b1fefb38120"),
                            Price = 1008m
                        },
                        new
                        {
                            ColorId = new Guid("700b2a28-ea84-419c-bf6d-7fe1126b4b4b"),
                            ProductId = new Guid("a3478123-d608-4032-b447-b634a2dec89c"),
                            StorageId = new Guid("80c335a6-eaae-42eb-a83a-0d7f47dc543a"),
                            Price = 1080m
                        },
                        new
                        {
                            ColorId = new Guid("700b2a28-ea84-419c-bf6d-7fe1126b4b4b"),
                            ProductId = new Guid("a3478123-d608-4032-b447-b634a2dec89c"),
                            StorageId = new Guid("c1d112fd-5a18-415d-9a5f-9cbc602095a2"),
                            Price = 1225m
                        },
                        new
                        {
                            ColorId = new Guid("ea32ab8f-e614-4327-955e-3b26670cc1c9"),
                            ProductId = new Guid("a3478123-d608-4032-b447-b634a2dec89c"),
                            StorageId = new Guid("2183be20-628e-480b-93e9-0b1fefb38120"),
                            Price = 1008m
                        },
                        new
                        {
                            ColorId = new Guid("ea32ab8f-e614-4327-955e-3b26670cc1c9"),
                            ProductId = new Guid("a3478123-d608-4032-b447-b634a2dec89c"),
                            StorageId = new Guid("80c335a6-eaae-42eb-a83a-0d7f47dc543a"),
                            Price = 1080m
                        },
                        new
                        {
                            ColorId = new Guid("ea32ab8f-e614-4327-955e-3b26670cc1c9"),
                            ProductId = new Guid("a3478123-d608-4032-b447-b634a2dec89c"),
                            StorageId = new Guid("c1d112fd-5a18-415d-9a5f-9cbc602095a2"),
                            Price = 1225m
                        },
                        new
                        {
                            ColorId = new Guid("30462f05-b486-4ee0-b2d8-364d5627145d"),
                            ProductId = new Guid("5b5087a0-5cac-4fde-b39d-d6fbdb7f5d57"),
                            StorageId = new Guid("80c335a6-eaae-42eb-a83a-0d7f47dc543a"),
                            Price = 950m
                        },
                        new
                        {
                            ColorId = new Guid("d6ffc78c-7ed0-4bd7-85a0-ac1677d31f59"),
                            ProductId = new Guid("fc386a0a-48a8-49e9-aff7-e0bf6902d3b3"),
                            StorageId = new Guid("80c335a6-eaae-42eb-a83a-0d7f47dc543a"),
                            Price = 1400m
                        },
                        new
                        {
                            ColorId = new Guid("0ec56401-7552-422d-8c91-e4ae41380fbc"),
                            ProductId = new Guid("fc386a0a-48a8-49e9-aff7-e0bf6902d3b3"),
                            StorageId = new Guid("80c335a6-eaae-42eb-a83a-0d7f47dc543a"),
                            Price = 1400m
                        },
                        new
                        {
                            ColorId = new Guid("ea32ab8f-e614-4327-955e-3b26670cc1c9"),
                            ProductId = new Guid("fc386a0a-48a8-49e9-aff7-e0bf6902d3b3"),
                            StorageId = new Guid("80c335a6-eaae-42eb-a83a-0d7f47dc543a"),
                            Price = 1400m
                        });
                });

            modelBuilder.Entity("ReactStore.Domain.Entities.Storage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Capacity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Storage", "reactstore");

                    b.HasData(
                        new
                        {
                            Id = new Guid("89493353-3f05-48d9-949c-01b302e377db"),
                            Capacity = "32GB"
                        },
                        new
                        {
                            Id = new Guid("2e26db98-f577-42be-b53e-e2e605514f03"),
                            Capacity = "64GB"
                        },
                        new
                        {
                            Id = new Guid("29b48bef-18cc-4210-a301-ef9cb89e05b0"),
                            Capacity = "128GB"
                        },
                        new
                        {
                            Id = new Guid("f3c480c6-8c53-45cf-8fd2-16129ed9bfc5"),
                            Capacity = "256GB"
                        },
                        new
                        {
                            Id = new Guid("c3e92cbd-3b6e-4a6e-a0c9-fb96c4fc7ebf"),
                            Capacity = "512GB"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("ReactStore.Domain.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("ReactStore.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("ReactStore.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("ReactStore.Domain.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReactStore.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("ReactStore.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReactStore.Domain.Entities.Image", b =>
                {
                    b.HasOne("ReactStore.Domain.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ReactStore.Domain.Entities.Product", b =>
                {
                    b.HasOne("ReactStore.Domain.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReactStore.Domain.Entities.OS", "OS")
                        .WithMany("Products")
                        .HasForeignKey("OSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("OS");
                });

            modelBuilder.Entity("ReactStore.Domain.Entities.ProductFeature", b =>
                {
                    b.HasOne("ReactStore.Domain.Entities.Feature", "Feature")
                        .WithMany("ProductFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReactStore.Domain.Entities.Product", "Product")
                        .WithMany("ProductFeatures")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ReactStore.Domain.Entities.ProductVariant", b =>
                {
                    b.HasOne("ReactStore.Domain.Entities.Color", "Color")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReactStore.Domain.Entities.Product", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReactStore.Domain.Entities.Storage", "Storage")
                        .WithMany("ProductVariants")
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Product");

                    b.Navigation("Storage");
                });

            modelBuilder.Entity("ReactStore.Domain.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ReactStore.Domain.Entities.Color", b =>
                {
                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("ReactStore.Domain.Entities.Feature", b =>
                {
                    b.Navigation("ProductFeatures");
                });

            modelBuilder.Entity("ReactStore.Domain.Entities.OS", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ReactStore.Domain.Entities.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("ProductFeatures");

                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("ReactStore.Domain.Entities.Storage", b =>
                {
                    b.Navigation("ProductVariants");
                });
#pragma warning restore 612, 618
        }
    }
}
